export const topBarData = {
  trustBadge: "⚡ ISO 9001:2015 Certified | Background Check & HR Verification Compliant",
  rating: "★ 4.9/5 Rating (14,800+ Careers Accelerated)",
  supportHours: "Mon - Sat: 9:00 AM - 8:00 PM IST",
  socialLinks: [
    {
      id: "fb",
      name: "Facebook",
      url: "https://www.facebook.com",
      iconType: "facebook",
    },
    {
      id: "li",
      name: "LinkedIn",
      url: "https://www.linkedin.com",
      iconType: "linkedin",
    },
    {
      id: "wa",
      name: "WhatsApp Direct",
      url: "https://wa.me/919028760099",
      iconType: "whatsapp",
    },
  ],
};

export const whatsappContact = {
  tagline: "Official WhatsApp Desk",
  label: "Live Verification Officer",
  number: "+91 9028760099",
  rawNumber: "9028760099",
  link: "https://wa.me/919028760099?text=Hello%20Career%20Consultancy%2C%20I%20would%20like%20to%20get%20a%20priority%20consultation.",
};

export const brandData = {
  title: "CAREER",
  subtitle: "CONSULTANCY",
  badge: "GOVT. RECOGNIZED",
  homePath: "/",
};

export const navItems = [
  {
    id: "home",
    title: "Home",
    path: "/",
  },
  {
    id: "why-us",
    title: "Why Us",
    path: "/why-us",
  },
  {
    id: "our-services",
    title: "Our Services",
    path: "/services",
    hasDropdown: true,
    dropdownItems: [
      {
        id: "exp-cert",
        title: "Experience Certificate",
        path: "/services/experience-certificate",
        desc: "HR-authorized employment records with official telephonic & email verification support.",
        highlights: ["BGC & EPFO Verified", "HR Domain Support", "Express Delivery"],
        icon: "file-text",
        badge: "Most Requested",
        gradient: "from-emerald-500 to-teal-600",
      },
      {
        id: "visa-doc",
        title: "Visa Documentation",
        path: "/services/visa-documentation",
        desc: "Comprehensive work & study visa paperwork prepared as per strict embassy standards.",
        highlights: ["Apostille Certified", "Global Embassies", "Confidential Review"],
        icon: "globe",
        badge: "Embassy Grade",
        gradient: "from-blue-500 to-indigo-600",
      },
      {
        id: "projects-training",
        title: "Real Time Projects Training",
        path: "/services/real-time-projects-training",
        desc: "Live enterprise codebases, production deployments, and technical interview defense.",
        highlights: ["Industry Architect Lead", "Real Production Repos", "Interview Shield"],
        icon: "laptop",
        badge: "High Impact",
        gradient: "from-amber-500 to-orange-600",
      },
    ],
  },
  {
    id: "location",
    title: "Locations",
    path: "/location",
    hasDropdown: true,
    dropdownItems: [
      { title: "Bengaluru", path: "/location/bengaluru", state: "Karnataka", hub: "Silicon Valley of India" },
      { title: "Hyderabad", path: "/location/hyderabad", state: "Telangana", hub: "HITEC City" },
      { title: "Pune", path: "/location/pune", state: "Maharashtra", hub: "Hinjawadi / Magarpatta" },
      { title: "Chennai", path: "/location/chennai", state: "Tamil Nadu", hub: "OMR Tech Corridor" },
      { title: "Gurugram", path: "/location/gurugram", state: "Haryana", hub: "Cyber City NCR" },
      { title: "Noida", path: "/location/noida", state: "Uttar Pradesh", hub: "Sector 62 / Expressway" },
      { title: "Mumbai", path: "/location/mumbai", state: "Maharashtra", hub: "BKC & Powai" },
      { title: "Kolkata", path: "/location/kolkata", state: "West Bengal", hub: "Sector V Salt Lake" },
      { title: "Ahmedabad", path: "/location/ahmedabad", state: "Gujarat", hub: "GIFT City / SG Highway" },
      { title: "Kochi", path: "/location/kochi", state: "Kerala", hub: "Infopark Kakkanad" },
      { title: "Thiruvananthapuram", path: "/location/thiruvananthapuram", state: "Kerala", hub: "Technopark" },
      { title: "Coimbatore", path: "/location/coimbatore", state: "Tamil Nadu", hub: "Tidel Park" },
      { title: "Jaipur", path: "/location/jaipur", state: "Rajasthan", hub: "Mahindra World City" },
      { title: "Indore", path: "/location/indore", state: "Madhya Pradesh", hub: "Super Corridor" },
      { title: "Bhubaneswar", path: "/location/bhubaneswar", state: "Odisha", hub: "Infocity" },
      { title: "Chandigarh (Mohali)", path: "/location/chandigarh-mohali", state: "Punjab", hub: "IT City" },
      { title: "Gandhinagar", path: "/location/gandhinagar", state: "Gujarat", hub: "Infocity SEZ" },
      { title: "Visakhapatnam", path: "/location/visakhapatnam", state: "Andhra Pradesh", hub: "Rushikonda Hills" },
      { title: "Nagpur", path: "/location/nagpur", state: "Maharashtra", hub: "MIHAN SEZ" },
      { title: "Lucknow", path: "/location/lucknow", state: "Uttar Pradesh", hub: "HCL IT City" },
      { title: "Mysore", path: "/location/mysore", state: "Karnataka", hub: "Hebbal Industrial Area" },
      { title: "Vadodara", path: "/location/vadodara", state: "Gujarat", hub: "Alkapuri Hub" },
      { title: "Surat", path: "/location/surat", state: "Gujarat", hub: "Diamond & IT Corridor" },
      { title: "Mangaluru", path: "/location/mangaluru", state: "Karnataka", hub: "Infosys SEZ" },
      { title: "Tiruchirappalli (Trichy)", path: "/location/tiruchirappalli", state: "Tamil Nadu", hub: "ELCOT IT Park" },
      { title: "Nashik", path: "/location/nashik", state: "Maharashtra", hub: "Ambad & Satpur" },
      { title: "Bhopal", path: "/location/bhopal", state: "Madhya Pradesh", hub: "Bhadbhada Road" },
      { title: "Madurai", path: "/location/madurai", state: "Tamil Nadu", hub: "Vadapalanji IT SEZ" },
      { title: "Vijayawada", path: "/location/vijayawada", state: "Andhra Pradesh", hub: "Medha IT Park" },
      { title: "Kozhikode", path: "/location/kozhikode", state: "Kerala", hub: "Cyberpark" },
    ],
  },
  {
    id: "blog",
    title: "Blog",
    path: "/blog",
  },
  {
    id: "contact-us",
    title: "Contact Us",
    path: "/contact",
  },
];
